import { Link } from 'wouter';
import { Navbar } from '@/components/site/Navbar';
import { Footer } from '@/components/site/Footer';
import { Eyebrow, Section } from '@/components/site/primitives';
import { useDocumentMeta } from '@/hooks/use-document-meta';

const TITLE = 'Terms of Use — Airavoto Gaming POS';
const DESCRIPTION = 'Terms of use for Airavoto Gaming POS.';

const sections = [
  {
    title: '1. Acceptance of terms',
    body: `By downloading, installing or using Airavoto Gaming POS ("the Software"), you agree to be bound by these Terms of Use. If you do not agree, do not install or use the Software.`,
  },
  {
    title: '2. License grant',
    body: `Subject to these terms, Airavoto grants you a worldwide, non-exclusive, royalty-free license to download, install and use the Software for your own commercial or non-commercial purposes.\n\nYou may not:\n• Resell or sublicense the Software as a standalone product\n• Remove or alter copyright notices within the source code\n• Represent the Software as your own original work when distributing it`,
  },
  {
    title: '3. Free of charge',
    body: `The Software is provided free of charge. There are no subscription fees, seat licence fees, module unlock fees or any other charges associated with downloading, installing or using the Software. Future updates are also free.`,
  },
  {
    title: '4. Self-hosted deployment',
    body: `The Software is designed to be installed and operated on hardware you own or control. You are solely responsible for:\n\n• The security and integrity of your installation\n• Maintaining regular database backups\n• Keeping dependencies (Node.js, PostgreSQL) up to date\n• Complying with all applicable laws and regulations in your jurisdiction, including data protection laws relating to your customers' personal data`,
  },
  {
    title: '5. No warranty',
    body: `THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.\n\nAiravoto does not warrant that the Software will be error-free, uninterrupted, or free of security vulnerabilities. You use the Software at your own risk.`,
  },
  {
    title: '6. Limitation of liability',
    body: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, AIRAVOTO SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF DATA, LOSS OF REVENUE OR LOSS OF BUSINESS, ARISING OUT OF OR IN CONNECTION WITH THE USE OR INABILITY TO USE THE SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\n\nIn no event shall Airavoto's total liability to you exceed the amount you paid for the Software (which is zero).`,
  },
  {
    title: '7. Third-party components',
    body: `The Software includes open-source third-party libraries (React, Express, Drizzle ORM, PostgreSQL, etc.) each governed by their own licenses. A full list of dependencies and their licenses is available in the package.json file distributed with the Software.`,
  },
  {
    title: '8. Modifications and contributions',
    body: `You are welcome to modify the Software for your own use. If you submit contributions to the project (via pull requests or issues), you grant Airavoto a perpetual, worldwide, royalty-free license to use, modify and distribute those contributions as part of the Software.`,
  },
  {
    title: '9. Termination',
    body: `Your license to use the Software is effective until terminated. It terminates automatically if you breach any of these terms. Upon termination, you must cease using the Software and delete all copies from your systems.`,
  },
  {
    title: '10. Governing law',
    body: `These Terms are governed by the laws of India. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts in India.`,
  },
  {
    title: '11. Data sync with Airavoto Gaming platform',
    body: `By installing and using Airavoto Gaming POS, you agree that real-time operational data generated by your center — including seat availability, active session status for PC, PS5, Xbox, VR and other device types — will be synchronised with the Airavoto Gaming web platform ("the Platform").\n\nThe Platform is a publicly accessible application that allows gaming users to discover real-time seat availability at registered gaming centers in their area. This sync is a core part of the Airavoto ecosystem and is mandatory for all installations.\n\n**What data is synced:**\n• Live seat availability per device type (PC, PS5, Xbox, VR, simulators)\n• Current occupancy count and open slots\n• Center name, location and operating hours (as configured in Center Info)\n• No personal customer data, financial data or staff credentials are ever synced\n\n**Mandatory compliance:**\nSync with the Airavoto Gaming platform is a condition of using this Software. Gaming centers that disable, block or interfere with the sync mechanism will be in breach of these Terms and will be permanently banned from using the Software, including all future updates. Banned installations will cease to receive security patches and feature releases.\n\nBy continuing to use the Software, you explicitly consent to this data sync and confirm that you have informed your customers that your center's real-time seat availability is visible on the Airavoto Gaming platform.`,
  },
  {
    title: '12. Changes to these terms',
    body: `We may update these Terms from time to time. Material changes will be noted in the Changelog. Continued use of the Software after an update constitutes acceptance of the revised Terms.`,
  },
];

export default function Terms() {
  useDocumentMeta({ title: TITLE, description: DESCRIPTION, image: '/airavoto-logo.png' });

  return (
    <main className="min-h-screen bg-background text-foreground">
      <Navbar />

      <section className="relative overflow-hidden pb-12 pt-36 sm:pt-44">
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0"
          style={{ background: 'radial-gradient(60% 45% at 50% 0%, oklch(0.75 0.10 290/0.18), transparent 70%)' }}
        />
        <div className="relative mx-auto w-full max-w-6xl px-5 text-center">
          <Eyebrow>Legal</Eyebrow>
          <h1 className="mx-auto mt-8 max-w-3xl text-balance text-5xl font-bold leading-[1.02] tracking-[-0.03em] sm:text-6xl">
            Terms of Use
          </h1>
          <p className="mx-auto mt-4 text-sm text-muted-foreground">Last updated: July 2026</p>
        </div>
      </section>

      <Section>
        <div className="mx-auto max-w-3xl">
          <div className="rounded-2xl border border-border bg-surface p-6">
            <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">TL;DR</p>
            <p className="mt-3 text-base leading-relaxed text-foreground/90">
              The Software is free to use for any purpose. You're responsible for your own
              installation and data. We provide it as-is with no warranty. Don't resell it as
              your own product.
            </p>
          </div>

          <div className="mt-10 space-y-10">
            {sections.map((s) => (
              <div key={s.title}>
                <h2 className="text-lg font-semibold tracking-tight">{s.title}</h2>
                <div className="mt-3 space-y-3">
                  {s.body.split('\n\n').map((para, i) => (
                    <p key={i} className="whitespace-pre-line text-sm leading-relaxed text-muted-foreground">
                      {para}
                    </p>
                  ))}
                </div>
              </div>
            ))}
          </div>

          <div className="mt-12 flex flex-wrap gap-4 border-t border-border/60 pt-8 text-sm">
            <Link href="/privacy" className="text-foreground/80 hover:text-foreground">
              Privacy Policy →
            </Link>
            <Link href="/faq" className="text-foreground/80 hover:text-foreground">
              FAQ →
            </Link>
          </div>
        </div>
      </Section>

      <Footer />
    </main>
  );
}
